/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.107
 * Generated at: 2025-08-18 13:32:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_002dtable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\"\r\n");
      out.write("	href=\"plugins/images/favicon.png\">\r\n");
      out.write("<title>Pixel Admin</title>\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"bootstrap/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Menu CSS -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css\">\r\n");
      out.write("<!-- animation CSS -->\r\n");
      out.write("<link href=\"css/animate.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- color CSS -->\r\n");
      out.write("<link href=\"css/colors/blue-dark.css\" id=\"theme\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/custom.css\">\r\n");
      out.write("<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Preloader -->\r\n");
      out.write("	<div class=\"preloader\">\r\n");
      out.write("		<div class=\"cssload-speeding-wheel\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"wrapper\">\r\n");
      out.write("		<!-- Navigation -->\r\n");
      out.write("		<nav class=\"navbar navbar-default navbar-static-top m-b-0\">\r\n");
      out.write("			<div class=\"navbar-header\">\r\n");
      out.write("				<a class=\"navbar-toggle hidden-sm hidden-md hidden-lg \"\r\n");
      out.write("					href=\"javascript:void(0)\" data-toggle=\"collapse\"\r\n");
      out.write("					data-target=\".navbar-collapse\"> <i class=\"fa fa-bars\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("				<div class=\"top-left-part\">\r\n");
      out.write("					<a class=\"logo\" href=\"index.html\"> <b> <img\r\n");
      out.write("							src=\"plugins/images/pixeladmin-logo.png\" alt=\"home\" />\r\n");
      out.write("					</b> <span class=\"hidden-xs\"> <img\r\n");
      out.write("							src=\"plugins/images/pixeladmin-text.png\" alt=\"home\" />\r\n");
      out.write("					</span>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<ul class=\"nav navbar-top-links navbar-left m-l-20 hidden-xs\">\r\n");
      out.write("					<li>\r\n");
      out.write("						<form role=\"search\" class=\"app-search hidden-xs\">\r\n");
      out.write("							<input type=\"text\" placeholder=\"Search...\" class=\"form-control\">\r\n");
      out.write("							<a href=\"\"> <i class=\"fa fa-search\"></i>\r\n");
      out.write("							</a>\r\n");
      out.write("						</form>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<ul class=\"nav navbar-top-links navbar-right pull-right\">\r\n");
      out.write("					<li>\r\n");
      out.write("						<div class=\"dropdown\">\r\n");
      out.write("							<a class=\"profile-pic dropdown-toggle\" data-toggle=\"dropdown\"\r\n");
      out.write("								href=\"#\"> <img src=\"plugins/images/users/varun.jpg\"\r\n");
      out.write("								alt=\"user-img\" width=\"36\" class=\"img-circle\" /> <b\r\n");
      out.write("								class=\"hidden-xs\">Cybersoft</b>\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul class=\"dropdown-menu\">\r\n");
      out.write("								<li><a href=\"profile.html\">Thông tin cá nhân</a></li>\r\n");
      out.write("								<li><a href=\"#\">Thống kê công việc</a></li>\r\n");
      out.write("								<li class=\"divider\"></li>\r\n");
      out.write("								<li><a href=\"#\">Đăng xuất</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- /.navbar-header -->\r\n");
      out.write("			<!-- /.navbar-top-links -->\r\n");
      out.write("			<!-- /.navbar-static-side -->\r\n");
      out.write("		</nav>\r\n");
      out.write("		<!-- Left navbar-header -->\r\n");
      out.write("		<div class=\"navbar-default sidebar\" role=\"navigation\">\r\n");
      out.write("			<div class=\"sidebar-nav navbar-collapse slimscrollsidebar\">\r\n");
      out.write("				<ul class=\"nav\" id=\"side-menu\">\r\n");
      out.write("					<li style=\"padding: 10px 0 0;\"><a href=\"index.html\"\r\n");
      out.write("						class=\"waves-effect\"><i class=\"fa fa-clock-o fa-fw\"\r\n");
      out.write("							aria-hidden=\"true\"></i><span class=\"hide-menu\">Dashboard</span></a></li>\r\n");
      out.write("					<li><a href=\"user-table.html\" class=\"waves-effect\"><i\r\n");
      out.write("							class=\"fa fa-user fa-fw\" aria-hidden=\"true\"></i><span\r\n");
      out.write("							class=\"hide-menu\">Thành viên</span></a></li>\r\n");
      out.write("					<li><a href=\"role-table.html\" class=\"waves-effect\"><i\r\n");
      out.write("							class=\"fa fa-modx fa-fw\" aria-hidden=\"true\"></i><span\r\n");
      out.write("							class=\"hide-menu\">Quyền</span></a></li>\r\n");
      out.write("					<li><a href=\"groupwork.html\" class=\"waves-effect\"><i\r\n");
      out.write("							class=\"fa fa-table fa-fw\" aria-hidden=\"true\"></i><span\r\n");
      out.write("							class=\"hide-menu\">Dự án</span></a></li>\r\n");
      out.write("					<li><a href=\"task.html\" class=\"waves-effect\"><i\r\n");
      out.write("							class=\"fa fa-table fa-fw\" aria-hidden=\"true\"></i><span\r\n");
      out.write("							class=\"hide-menu\">Công việc</span></a></li>\r\n");
      out.write("					<li><a href=\"blank.html\" class=\"waves-effect\"><i\r\n");
      out.write("							class=\"fa fa-columns fa-fw\" aria-hidden=\"true\"></i><span\r\n");
      out.write("							class=\"hide-menu\">Blank Page</span></a></li>\r\n");
      out.write("					<li><a href=\"404.html\" class=\"waves-effect\"><i\r\n");
      out.write("							class=\"fa fa-info-circle fa-fw\" aria-hidden=\"true\"></i><span\r\n");
      out.write("							class=\"hide-menu\">Error 404</span></a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Left navbar-header end -->\r\n");
      out.write("		<!-- Page Content -->\r\n");
      out.write("		<div id=\"page-wrapper\">\r\n");
      out.write("			<div class=\"container-fluid\">\r\n");
      out.write("				<div class=\"row bg-title\">\r\n");
      out.write("					<div class=\"col-lg-3 col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("						<h4 class=\"page-title\">Danh sách thành viên</h4>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-9 col-sm-8 col-md-8 col-xs-12 text-right\">\r\n");
      out.write("						<a href=\"user-add.html\" class=\"btn btn-sm btn-success\">Thêm\r\n");
      out.write("							mới</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- /.col-lg-12 -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- /row -->\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-sm-12\">\r\n");
      out.write("						<div class=\"white-box\">\r\n");
      out.write("							<div class=\"table-responsive\">\r\n");
      out.write("								<table class=\"table\" id=\"example\">\r\n");
      out.write("									<thead>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<th>STT</th>\r\n");
      out.write("											<th>First Name</th>\r\n");
      out.write("											<th>Last Name</th>\r\n");
      out.write("											<th>Username</th>\r\n");
      out.write("											<th>Role</th>\r\n");
      out.write("											<th>#</th>\r\n");
      out.write("										</tr>\r\n");
      out.write("									</thead>\r\n");
      out.write("									<tbody>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td>1</td>\r\n");
      out.write("											<td>Deshmukh</td>\r\n");
      out.write("											<td>Prohaska</td>\r\n");
      out.write("											<td>@Genelia</td>\r\n");
      out.write("											<td>admin</td>\r\n");
      out.write("											<td><a href=\"#\" class=\"btn btn-sm btn-primary\">Sửa</a> <a\r\n");
      out.write("												href=\"#\" class=\"btn btn-sm btn-danger\">Xóa</a> <a\r\n");
      out.write("												href=\"user-details.html\" class=\"btn btn-sm btn-info\">Xem</a>\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td>2</td>\r\n");
      out.write("											<td>Deshmukh</td>\r\n");
      out.write("											<td>Gaylord</td>\r\n");
      out.write("											<td>@Ritesh</td>\r\n");
      out.write("											<td>member</td>\r\n");
      out.write("											<td><a href=\"#\" class=\"btn btn-sm btn-primary\">Sửa</a> <a\r\n");
      out.write("												href=\"user-delete?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"btn btn-sm btn-danger\">Xóa</a> <a\r\n");
      out.write("												href=\"user-details.html\" class=\"btn btn-sm btn-info\">Xem</a>\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td>3</td>\r\n");
      out.write("											<td>Sanghani</td>\r\n");
      out.write("											<td>Gusikowski</td>\r\n");
      out.write("											<td>@Govinda</td>\r\n");
      out.write("											<td>developer</td>\r\n");
      out.write("											<td><a href=\"#\" class=\"btn btn-sm btn-primary\">Sửa</a> <a\r\n");
      out.write("												href=\"#\" class=\"btn btn-sm btn-danger\">Xóa</a> <a\r\n");
      out.write("												href=\"user-details.html\" class=\"btn btn-sm btn-info\">Xem</a>\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td>4</td>\r\n");
      out.write("											<td>Roshan</td>\r\n");
      out.write("											<td>Rogahn</td>\r\n");
      out.write("											<td>@Hritik</td>\r\n");
      out.write("											<td>supporter</td>\r\n");
      out.write("											<td><a href=\"#\" class=\"btn btn-sm btn-primary\">Sửa</a> <a\r\n");
      out.write("												href=\"#\" class=\"btn btn-sm btn-danger\">Xóa</a> <a\r\n");
      out.write("												href=\"user-details.html\" class=\"btn btn-sm btn-info\">Xem</a>\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td>5</td>\r\n");
      out.write("											<td>Joshi</td>\r\n");
      out.write("											<td>Hickle</td>\r\n");
      out.write("											<td>@Maruti</td>\r\n");
      out.write("											<td>member</td>\r\n");
      out.write("											<td><a href=\"#\" class=\"btn btn-sm btn-primary\">Sửa</a> <a\r\n");
      out.write("												href=\"#\" class=\"btn btn-sm btn-danger\">Xóa</a> <a\r\n");
      out.write("												href=\"user-details.html\" class=\"btn btn-sm btn-info\">Xem</a>\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td>6</td>\r\n");
      out.write("											<td>Nigam</td>\r\n");
      out.write("											<td>Eichmann</td>\r\n");
      out.write("											<td>@Sonu</td>\r\n");
      out.write("											<td>supporter</td>\r\n");
      out.write("											<td><a href=\"#\" class=\"btn btn-sm btn-primary\">Sửa</a> <a\r\n");
      out.write("												href=\"#\" class=\"btn btn-sm btn-danger\">Xóa</a> <a\r\n");
      out.write("												href=\"user-details.html\" class=\"btn btn-sm btn-info\">Xem</a>\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td>1</td>\r\n");
      out.write("											<td>Deshmukh</td>\r\n");
      out.write("											<td>Prohaska</td>\r\n");
      out.write("											<td>@Genelia</td>\r\n");
      out.write("											<td>admin</td>\r\n");
      out.write("											<td><a href=\"#\" class=\"btn btn-sm btn-primary\">Sửa</a> <a\r\n");
      out.write("												href=\"#\" class=\"btn btn-sm btn-danger\">Xóa</a> <a\r\n");
      out.write("												href=\"user-details.html\" class=\"btn btn-sm btn-info\">Xem</a>\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td>2</td>\r\n");
      out.write("											<td>Deshmukh</td>\r\n");
      out.write("											<td>Gaylord</td>\r\n");
      out.write("											<td>@Ritesh</td>\r\n");
      out.write("											<td>member</td>\r\n");
      out.write("											<td><a href=\"#\" class=\"btn btn-sm btn-primary\">Sửa</a> <a\r\n");
      out.write("												href=\"#\" class=\"btn btn-sm btn-danger\">Xóa</a> <a\r\n");
      out.write("												href=\"user-details.html\" class=\"btn btn-sm btn-info\">Xem</a>\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td>3</td>\r\n");
      out.write("											<td>Sanghani</td>\r\n");
      out.write("											<td>Gusikowski</td>\r\n");
      out.write("											<td>@Govinda</td>\r\n");
      out.write("											<td>developer</td>\r\n");
      out.write("											<td><a href=\"#\" class=\"btn btn-sm btn-primary\">Sửa</a> <a\r\n");
      out.write("												href=\"#\" class=\"btn btn-sm btn-danger\">Xóa</a> <a\r\n");
      out.write("												href=\"user-details.html\" class=\"btn btn-sm btn-info\">Xem</a>\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td>4</td>\r\n");
      out.write("											<td>Roshan</td>\r\n");
      out.write("											<td>Rogahn</td>\r\n");
      out.write("											<td>@Hritik</td>\r\n");
      out.write("											<td>supporter</td>\r\n");
      out.write("											<td><a href=\"#\" class=\"btn btn-sm btn-primary\">Sửa</a> <a\r\n");
      out.write("												href=\"#\" class=\"btn btn-sm btn-danger\">Xóa</a> <a\r\n");
      out.write("												href=\"user-details.html\" class=\"btn btn-sm btn-info\">Xem</a>\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td>5</td>\r\n");
      out.write("											<td>Joshi</td>\r\n");
      out.write("											<td>Hickle</td>\r\n");
      out.write("											<td>@Maruti</td>\r\n");
      out.write("											<td>member</td>\r\n");
      out.write("											<td><a href=\"#\" class=\"btn btn-sm btn-primary\">Sửa</a> <a\r\n");
      out.write("												href=\"#\" class=\"btn btn-sm btn-danger\">Xóa</a> <a\r\n");
      out.write("												href=\"user-details.html\" class=\"btn btn-sm btn-info\">Xem</a>\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td>6</td>\r\n");
      out.write("											<td>Nigam</td>\r\n");
      out.write("											<td>Eichmann</td>\r\n");
      out.write("											<td>@Sonu</td>\r\n");
      out.write("											<td>supporter</td>\r\n");
      out.write("											<td><a href=\"#\" class=\"btn btn-sm btn-primary\">Sửa</a> <a\r\n");
      out.write("												href=\"#\" class=\"btn btn-sm btn-danger\">Xóa</a> <a\r\n");
      out.write("												href=\"user-details.html\" class=\"btn btn-sm btn-info\">Xem</a>\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("									</tbody>\r\n");
      out.write("								</table>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- /.row -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- /.container-fluid -->\r\n");
      out.write("			<footer class=\"footer text-center\"> 2018 &copy; myclass.com\r\n");
      out.write("			</footer>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- /#page-wrapper -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- /#wrapper -->\r\n");
      out.write("	<!-- jQuery -->\r\n");
      out.write("	<script src=\"plugins/bower_components/jquery/dist/jquery.min.js\"></script>\r\n");
      out.write("	<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("	<script src=\"bootstrap/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<!-- Menu Plugin JavaScript -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js\"></script>\r\n");
      out.write("	<!--slimscroll JavaScript -->\r\n");
      out.write("	<script src=\"js/jquery.slimscroll.js\"></script>\r\n");
      out.write("	<script src=\"js/jquery.dataTables.js\"></script>\r\n");
      out.write("	<!--Wave Effects -->\r\n");
      out.write("	<script src=\"js/waves.js\"></script>\r\n");
      out.write("	<!-- Custom Theme JavaScript -->\r\n");
      out.write("	<script src=\"js/custom.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(document).ready(function() {\r\n");
      out.write("			$('#example').DataTable();\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
